package com.ttcs.meetingmanagement;
import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.web.server.ResponseStatusException;import java.time.OffsetDateTime;import java.time.format.DateTimeFormatter;import static org.assertj.core.api.Assertions.*;
@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:us25test;MODE=MySQL","spring.datasource.driver-class-name=org.h2.Driver","spring.jpa.hibernate.ddl-auto=create-drop"})
class ChatbotBookingServiceTest{
  @Autowired ChatbotBookingService service;@Autowired ChatConversationService chat;@Autowired RoomRepository rooms;@Autowired UserDirectoryRepository users;
  @Test void rejectsOverlappingBooking(){seedUser("u1");if(!rooms.existsById("ROOM-A"))rooms.save(new Room("ROOM-A","Phong A",6,"Tang 1"));var start=OffsetDateTime.now().plusDays(1);var q=new ChatBookingRequest("u1","Hop",start,start.plusHours(1),4,"ROOM-A");service.book(q);assertThatThrownBy(()->service.book(q)).isInstanceOf(ResponseStatusException.class).hasMessageContaining("409 CONFLICT");}
  @Test void completesGuidedChatAndBooksRoom(){seedUser("chat-user");if(!rooms.existsById("ROOM-C"))rooms.save(new Room("ROOM-C","Phong C",30,"Tang 3"));String session=null;ChatMessageResponse response=chat.reply(new ChatMessageRequest(session,"chat-user"));session=response.sessionId();assertThat(response.step()).isEqualTo("TITLE");response=chat.reply(new ChatMessageRequest(session,"Hop chatbot"));assertThat(response.step()).isEqualTo("START");OffsetDateTime start=OffsetDateTime.now().plusDays(3).withSecond(0).withNano(0);DateTimeFormatter format=DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");chat.reply(new ChatMessageRequest(session,start.format(format)));chat.reply(new ChatMessageRequest(session,start.plusHours(1).format(format)));chat.reply(new ChatMessageRequest(session,"8"));response=chat.reply(new ChatMessageRequest(session,"không"));assertThat(response.step()).isEqualTo("ROOM");assertThat(response.roomOptions()).extracting(AvailableRoom::id).contains("ROOM-C").doesNotContain("ROOM-A");response=chat.reply(new ChatMessageRequest(session,"ROOM-C"));assertThat(response.step()).isEqualTo("CONFIRM");response=chat.reply(new ChatMessageRequest(session,"xác nhận"));assertThat(response.step()).isEqualTo("DONE");assertThat(response.booking()).isNotNull();assertThat(response.booking().roomId()).isEqualTo("ROOM-C");}
  @Test void listsOnlyRoomsThatAreLargeEnoughAndFree(){seedUser("availability-user");if(!rooms.existsById("ROOM-SMALL"))rooms.save(new Room("ROOM-SMALL","Phong nho",2,"Tang 1"));if(!rooms.existsById("ROOM-FREE"))rooms.save(new Room("ROOM-FREE","Phong trong",10,"Tang 2"));if(!rooms.existsById("ROOM-BUSY"))rooms.save(new Room("ROOM-BUSY","Phong ban",10,"Tang 2"));OffsetDateTime start=OffsetDateTime.now().plusDays(8).withSecond(0).withNano(0);service.book(new ChatBookingRequest("availability-user","Lich da co",start,start.plusHours(1),4,"ROOM-BUSY"));assertThat(service.availableRooms(start.plusMinutes(15),start.plusMinutes(45),4)).extracting(AvailableRoom::id).contains("ROOM-FREE").doesNotContain("ROOM-SMALL","ROOM-BUSY");}
  private void seedUser(String id){if(!users.existsById(id)){UserDirectoryEntry u=new UserDirectoryEntry();u.id=id;u.fullName="Nguoi dat";u.email=id+"@example.com";u.status="ACTIVE";users.save(u);}}
}
