package com.ttcs.meetingmanagement;

import jakarta.persistence.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*;
import org.springframework.boot.*; import org.springframework.boot.autoconfigure.SpringBootApplication; import org.springframework.context.annotation.Bean;
import org.springframework.data.jpa.repository.JpaRepository; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
import java.time.OffsetDateTime; import java.util.*; import com.fasterxml.jackson.annotation.JsonAutoDetect;

@SpringBootApplication public class MeetingManagementApplication { public static void main(String[] a){SpringApplication.run(MeetingManagementApplication.class,a);} @Bean BCryptPasswordEncoder encoder(){return new BCryptPasswordEncoder();} }

@JsonAutoDetect(fieldVisibility=JsonAutoDetect.Visibility.ANY)
@Entity @Table(name="roles") class Role { @Id @Column(name="role_id") String id; @Column(name="role_name",nullable=false,unique=true) String name; protected Role(){} Role(String i,String n){id=i;name=n;} }
@JsonAutoDetect(fieldVisibility=JsonAutoDetect.Visibility.ANY)
@Entity @Table(name="departments",uniqueConstraints=@UniqueConstraint(name="uk_department_hrm_code",columnNames="hrm_code")) class Department { @Id @Column(name="department_id") String id; @Column(name="department_name",nullable=false) String name; @Column(name="hrm_code") String hrmCode; @Column(name="last_synced_at") OffsetDateTime lastSyncedAt; protected Department(){} Department(String i,String n){id=i;name=n;} }
@Entity @Table(name="users",uniqueConstraints={@UniqueConstraint(name="uk_user_hrm_code",columnNames="hrm_code"),@UniqueConstraint(name="uk_user_email",columnNames="email")}) class User { @Id @Column(name="user_id",length=36) String id; @Column(name="role_id",nullable=false) String roleId; @Column(name="department_id") String departmentId; @Column(name="hrm_code") String hrmCode; @Column(name="full_name",nullable=false) String fullName; @Column(nullable=false) String email; String phone; @Column(nullable=false) String status="ACTIVE"; @Column(name="password_hash") String passwordHash; @Column(name="created_at",nullable=false) OffsetDateTime createdAt; @Column(name="updated_at",nullable=false) OffsetDateTime updatedAt; @Column(name="last_synced_at") OffsetDateTime lastSyncedAt; @PrePersist void create(){if(id==null)id=UUID.randomUUID().toString();createdAt=updatedAt=OffsetDateTime.now();} @PreUpdate void update(){updatedAt=OffsetDateTime.now();} }
interface RoleRepository extends JpaRepository<Role,String>{} interface DepartmentRepository extends JpaRepository<Department,String>{} interface UserRepository extends JpaRepository<User,String>{boolean existsByEmailIgnoreCase(String email);}
record CreateUserRequest(@NotBlank String fullName,@Email @NotBlank String email,@Pattern(regexp="^$|^[0-9+() .-]{7,20}$") String phone,@NotBlank @Size(min=8,max=72) String password,@NotBlank String roleId,String departmentId){}
record UserResponse(String id,String fullName,String email,String phone,String status,String roleId,String departmentId,OffsetDateTime createdAt){static UserResponse of(User u){return new UserResponse(u.id,u.fullName,u.email,u.phone,u.status,u.roleId,u.departmentId,u.createdAt);}}
@Service class UserService { final UserRepository users; final RoleRepository roles; final DepartmentRepository departments; final BCryptPasswordEncoder encoder; UserService(UserRepository u,RoleRepository r,DepartmentRepository d,BCryptPasswordEncoder e){users=u;roles=r;departments=d;encoder=e;} @Transactional UserResponse create(CreateUserRequest r){String email=r.email().trim().toLowerCase(); if(users.existsByEmailIgnoreCase(email))throw new ResponseStatusException(HttpStatus.CONFLICT,"Email đã tồn tại"); if(!roles.existsById(r.roleId()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Vai trò không tồn tại"); if(r.departmentId()!=null&&!r.departmentId().isBlank()&&!departments.existsById(r.departmentId()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Phòng ban không tồn tại"); User u=new User();u.fullName=r.fullName().trim();u.email=email;u.phone=r.phone();u.passwordHash=encoder.encode(r.password());u.roleId=r.roleId();u.departmentId=(r.departmentId()==null||r.departmentId().isBlank())?null:r.departmentId();return UserResponse.of(users.save(u));}}
@RestController @RequestMapping("/api") class UserController { final UserService service; final UserRepository users; final RoleRepository roles; final DepartmentRepository departments; UserController(UserService s,UserRepository u,RoleRepository r,DepartmentRepository d){service=s;users=u;roles=r;departments=d;} @PostMapping("/users") @ResponseStatus(HttpStatus.CREATED) UserResponse create(@Valid @RequestBody CreateUserRequest r){return service.create(r);} @GetMapping("/users") List<UserResponse> all(){return users.findAll().stream().map(UserResponse::of).toList();} @GetMapping("/roles") List<Role> roles(){return roles.findAll();} @GetMapping("/departments") List<Department> departments(){return departments.findAll();} }
@org.springframework.context.annotation.Configuration class SeedData { @Bean ApplicationRunner seed(RoleRepository r,DepartmentRepository d){return x->{if(r.count()==0)r.saveAll(List.of(new Role("ADMIN","Admin"),new Role("BOOKER","Người đặt lịch"),new Role("ATTENDEE","Người tham dự")));if(d.count()==0)d.save(new Department("DEP-IT","Công nghệ thông tin"));};} }
