spring.application.name=meetingmanagement
server.port=8080
<<<<<<< HEAD
spring.datasource.url=jdbc:h2:mem:meetingdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
=======

spring.datasource.url=jdbc:h2:file:./data/meetingdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
>>>>>>> e1f3f6bac2a4ff949c9d212475e9ffdfb21b5c94
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
