spring.application.name=meetingmanagement

server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/meeting_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=doclamcho

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true